# Generated by Django 3.1 on 2020-09-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_studentdetails'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentdetails',
            table='studentDetails',
        ),
        migrations.CreateModel(
            name='s_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travello.studentdetails')),
            ],
            options={
                'db_table': 's_info',
            },
        ),
    ]
