# Generated by Django 3.1 on 2020-09-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_auto_20200909_2248'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='s_info',
            table='student_info',
        ),
    ]
