# Generated by Django 3.1 on 2020-09-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oxygensupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=10)),
            ],
        ),
    ]
