# Generated by Django 3.1 on 2020-09-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('ward', models.CharField(max_length=20)),
                ('pyment_status', models.CharField(max_length=20)),
            ],
        ),
    ]
