# Generated by Django 3.1 on 2020-09-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('qualification', models.CharField(max_length=100)),
            ],
        ),
    ]
