# Generated by Django 3.1 on 2020-09-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
