# Generated by Django 3.1 on 2020-09-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200918_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookingjs',
        ),
    ]
