# Generated by Django 3.1 on 2020-09-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_bookingjs'),
    ]

    operations = [
        migrations.CreateModel(
            name='oxygensupply1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name1', models.CharField(max_length=100)),
                ('area1', models.CharField(max_length=20)),
                ('contact_no1', models.CharField(max_length=10)),
            ],
        ),
    ]
