# Generated by Django 3.1 on 2020-08-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitsl_name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('ICU', models.IntegerField()),
                ('ward', models.IntegerField()),
                ('oxygen_supply', models.CharField(max_length=10)),
            ],
        ),
    ]
