# Generated by Django 3.1 on 2020-09-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchinfo', '0004_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book',
        ),
    ]
