# Generated by Django 3.1 on 2020-09-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchinfo', '0006_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('qualification', models.TextField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchinfo.dept')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchinfo.information')),
            ],
        ),
    ]
